### ISSUE TITLE
Exercise 3.27: Leafs are counted while computing depth.

### ISSUE THREAD

**Issue by Tillaert** [brabant-scala/fp-redbook#10]
The book defines:

> Write a function `depth` that returns the maximum path length from the root of a tree to any leaf.

This does not include the leaf itself. However the test code includes the leaf. 

The [answer](https://github.com/fpinscala/fpinscala/blob/master/answerkey/datastructures/27.answer.scala) for the exercise does not count the leaf for calculating the depth.

**Comment by tikvar** [comment]
+1
