### ISSUE TITLE
Test 3.13 does not check folding direction.

### ISSUE THREAD

**Issue by Tillaert** [brabant-scala/fp-redbook#9]
The test defines tests such as:

`foldRight(List(1, 2, 3), 0)(_ - _) should be(2)`

but 

`foldRight(List(3, 2, 1), 0)(_ - _) should be(2)`

Also passes.

The function does not check whether foldRight folds from the right.

Details:

First example:

`1 - (2 - (3 - 0)) = 1 - (2 - 3) = 1 -( -1 ) = 2`

Second example

`3 - (2 - (1 - 0)) = 3 - (2 - 1) = 3 - ( 1 ) = 2`

Because for Seq(a,b,c):

`a - (b - (c - 0)) =a - (b - c) = a + c - b`

 ergo, a and c are interchangeable.)

**Comment by tikvar** [comment]
The existing test would work if it would have even length and the expected value is non-zero:
`1 - (2 - 0) = -1`
`1 - (2 - (3 - (4 - 0))) = -2`
vs
`2 - (1 - 0) = 1`
`4 - (3 - (2 - (1 - 0))) = 2`

In other words: For each number `k` and each list `L` of length `2*N` we have `foldRight(L,k) = - foldRight(reverse(L), k)`. This could then be encoded as a property based test, but I guess it's a bit of an overkill for this case.

**Comment by Tillaert** [comment]
In principle, a list of 2 elements would suffice, as long it is even in length and not empty.

This is due to the nature of the - operator.  To properly test processing order, we need an operation is order dependent (e.g. creating a new list or adding another shift method).

On the other hand, I would also be happy just to add another element to the test, because it is easier to read (which is important for these assignments. 

Property based tests would be great in production code, but would be too confusing in these tests (because they are not introduced until chapter 8).

**Comment by tikvar** [comment]
I am fine with both solutions, but since the PR is already there with the string concat test let's use that one. I'll review and approve it.
